//MOSTRAR INTRODUCCÍON DEL JUEGO, REGLAS Y COMO JUGAR.

//inicializar la variable (int) puntuacion
/* Recolectar la respuesta del usuario
string respuestaAbierta;
ConsoleKey respuestaTest;*/

//MOSTRAR PREGUNTA 

//RECOGER RESPUESTA DEL USUARIO

    //SI LA RESPUESTA ES CORRECTA

        //IMPRIMIR POR PANTALLA "LA RESPUESTA ES CORRECTA. SUMAS 10 PUNTOS"
        //SUMAR 10 PUNTOS A LA PUNTUACIÓN 

    //SI LA RESPUESTA ES CORRECTA

        //IMPRIMIR POR PANTALLA "LA RESPUESTA ES INCORRECTA. INIDICAR LA RESPUESTA CORRECTA"

//MOSTRAR PUNCIÓN FINAL. 